const state={pesquisa:null,eventos:[],influencias:[],resultados:[],chart:null,currentRows:[]};
function setStatus(m,t="info"){const b=document.getElementById("statusBox");b.textContent=m;b.className=`status ${t}`}
function compact(t,m=72){return !t?"":t.length>m?`${t.slice(0,m-1)}…`:t}
function k(o,d){return `${o}__${d}`}
async function loadPesquisa(){const{data,error}=await supabaseClient.from("pesquisas").select("id,codigo,titulo,status").eq("codigo",PESQUISA_CODIGO).single();if(error)throw new Error(`Erro ao carregar pesquisa: ${error.message}`);state.pesquisa=data}
async function loadEventos(){const{data,error}=await supabaseClient.from("eventos").select("id,numero,titulo,descricao,hipotese,ordem,ativo").eq("pesquisa_id",state.pesquisa.id).eq("ativo",true).order("ordem",{ascending:true});if(error)throw new Error(`Erro ao carregar eventos: ${error.message}`);state.eventos=data||[]}
async function loadInfluencias(){const{data,error}=await supabaseClient.from("influencias_eventos").select("id,pesquisa_id,evento_origem_id,evento_destino_id,intensidade,observacao").eq("pesquisa_id",state.pesquisa.id);if(error)throw new Error(`Erro ao carregar influências: ${error.message}`);state.influencias=data||[]}
async function loadResultados(){const{data,error}=await supabaseClient.from("motricidade_dependencia_eventos").select("*").order("ordem",{ascending:true});if(error)throw new Error(`Erro ao carregar resultados: ${error.message}`);state.resultados=data||[]}
function influenciaMap(){const map=new Map();state.influencias.forEach(i=>map.set(k(i.evento_origem_id,i.evento_destino_id),i));return map}
function renderMatrix(){const head=document.getElementById("matrixHead"),body=document.getElementById("matrixBody"),map=influenciaMap();head.innerHTML="";body.innerHTML="";const hr=document.createElement("tr");hr.innerHTML=`<th>Evento que influencia ↓ / Evento influenciado →</th>`;state.eventos.forEach(d=>{const th=document.createElement("th");th.innerHTML=`<div class="event-mini"><strong>E${d.numero}</strong><small>${compact(d.titulo,42)}</small></div>`;hr.appendChild(th)});head.appendChild(hr);state.eventos.forEach(o=>{const tr=document.createElement("tr"),td0=document.createElement("td");td0.innerHTML=`<div class="event-mini"><strong>E${o.numero} — ${o.titulo}</strong><small>Quanto este evento influencia os demais?</small></div>`;tr.appendChild(td0);state.eventos.forEach(d=>{const td=document.createElement("td");if(o.id===d.id){td.className="disabled-cell";td.textContent="—"}else{const item=map.get(k(o.id,d.id));const v=item?item.intensidade:0;td.innerHTML=`<select class="matrix-select" data-origem="${o.id}" data-destino="${d.id}"><option value="0" ${v===0?"selected":""}>0</option><option value="1" ${v===1?"selected":""}>1</option><option value="2" ${v===2?"selected":""}>2</option><option value="3" ${v===3?"selected":""}>3</option></select>`}tr.appendChild(td)});body.appendChild(tr)})}
function computeLocalResults(){const out=new Map(),inc=new Map();state.eventos.forEach(e=>{out.set(e.id,0);inc.set(e.id,0)});document.querySelectorAll(".matrix-select").forEach(s=>{const o=s.dataset.origem,d=s.dataset.destino,v=Number(s.value);out.set(o,(out.get(o)||0)+v);inc.set(d,(inc.get(d)||0)+v)});const rows=state.eventos.map(e=>({evento_id:e.id,numero:e.numero,titulo:e.titulo,motricidade:out.get(e.id)||0,dependencia:inc.get(e.id)||0}));const mm=rows.reduce((a,r)=>a+r.motricidade,0)/(rows.length||1),md=rows.reduce((a,r)=>a+r.dependencia,0)/(rows.length||1);return rows.map(r=>{let c,i;if(r.motricidade>=mm&&r.dependencia<md){c="evento motor";i="Influencia bastante o sistema e depende pouco dos demais eventos."}else if(r.motricidade>=mm&&r.dependencia>=md){c="evento de ligação";i="Influencia o sistema e também é bastante influenciado pelos demais eventos."}else if(r.motricidade<mm&&r.dependencia>=md){c="evento dependente";i="É mais resultado do sistema do que fator impulsionador."}else{c="evento autônomo";i="Tem baixa influência e baixa dependência em relação aos demais eventos."}return{...r,media_motricidade:mm,media_dependencia:md,classificacao:c,interpretacao:i}})}
const quadrantPlugin={id:"quadrantPlugin",afterDraw(chart){const{ctx,chartArea,scales}=chart;if(!chartArea)return;const rows=state.currentRows||state.resultados;if(!rows.length)return;const md=Number(rows[0].media_dependencia||0),mm=Number(rows[0].media_motricidade||0),x=scales.x.getPixelForValue(md),y=scales.y.getPixelForValue(mm);ctx.save();ctx.strokeStyle="rgba(40,79,125,.55)";ctx.lineWidth=1.5;ctx.setLineDash([6,5]);ctx.beginPath();ctx.moveTo(x,chartArea.top);ctx.lineTo(x,chartArea.bottom);ctx.moveTo(chartArea.left,y);ctx.lineTo(chartArea.right,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="rgba(23,32,24,.55)";ctx.font="700 12px system-ui";ctx.fillText("Motor",chartArea.left+12,chartArea.top+18);ctx.fillText("Ligação",x+12,chartArea.top+18);ctx.fillText("Autônomo",chartArea.left+12,chartArea.bottom-12);ctx.fillText("Dependente",x+12,chartArea.bottom-12);ctx.restore()}};
const pointLabelPlugin={id:"pointLabelPlugin",afterDatasetsDraw(chart){const{ctx}=chart;ctx.save();ctx.font="900 12px system-ui";ctx.fillStyle="#172018";chart.getDatasetMeta(0).data.forEach((p,i)=>{const r=chart.data.datasets[0].data[i];ctx.fillText(`E${r.numero}`,p.x+10,p.y-10)});ctx.restore()}};
function renderChart(rows=state.resultados){const ctx=document.getElementById("matrixChart");if(state.chart)state.chart.destroy();const maxMot=Math.max(1,...rows.map(r=>Number(r.motricidade))),maxDep=Math.max(1,...rows.map(r=>Number(r.dependencia)));state.currentRows=rows;state.chart=new Chart(ctx,{type:"scatter",data:{datasets:[{label:"Eventos",data:rows.map(r=>({x:Number(r.dependencia),y:Number(r.motricidade),numero:r.numero,titulo:r.titulo,classificacao:r.classificacao,interpretacao:r.interpretacao})),pointRadius:10,pointHoverRadius:13}]},options:{responsive:true,maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:c=>{const d=c.raw;return `E${d.numero}: dependência ${d.x}, motricidade ${d.y}`},afterLabel:c=>{const d=c.raw;return `${d.classificacao}: ${d.interpretacao}`}}},legend:{display:false}},scales:{x:{title:{display:true,text:"Dependência"},min:0,suggestedMax:maxDep+2,grid:{color:"rgba(23,32,24,.12)"}},y:{title:{display:true,text:"Motricidade"},min:0,suggestedMax:maxMot+2,grid:{color:"rgba(23,32,24,.12)"}}}},plugins:[quadrantPlugin,pointLabelPlugin]})}
function renderClassifications(rows=state.resultados){const grid=document.getElementById("classificationGrid");grid.innerHTML="";rows.forEach(r=>{const card=document.createElement("article");card.className="class-card";card.innerHTML=`<span>${r.classificacao}</span><strong>E${r.numero} — ${r.titulo}</strong><p><b>Motricidade:</b> ${r.motricidade} | <b>Dependência:</b> ${r.dependencia}</p><p>${r.interpretacao}</p>`;grid.appendChild(card)})}
function recalcLocal(){const rows=computeLocalResults();renderChart(rows);renderClassifications(rows);setStatus("Gráfico recalculado localmente. Clique em “Salvar no Supabase” para gravar as alterações.","success")}
async function saveMatrix(){setStatus("Salvando matriz no Supabase...","info");const payload=[];document.querySelectorAll(".matrix-select").forEach(s=>payload.push({pesquisa_id:state.pesquisa.id,evento_origem_id:s.dataset.origem,evento_destino_id:s.dataset.destino,intensidade:Number(s.value),observacao:"Valor editado pela interface de Motricidade × Dependência.",atualizado_em:new Date().toISOString()}));const{error}=await supabaseClient.from("influencias_eventos").upsert(payload,{onConflict:"pesquisa_id,evento_origem_id,evento_destino_id"});if(error)throw new Error(`Erro ao salvar matriz: ${error.message}`);await loadInfluencias();await loadResultados();renderMatrix();renderChart();renderClassifications();setStatus("Matriz salva e resultados atualizados.","success")}
function downloadText(filename,text,type="text/plain"){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function exportJson(){const data={pesquisa:state.pesquisa,resultados:state.currentRows||state.resultados,influencias:Array.from(document.querySelectorAll(".matrix-select")).map(s=>({evento_origem_id:s.dataset.origem,evento_destino_id:s.dataset.destino,intensidade:Number(s.value)}))};downloadText("motricidade_md2036.json",JSON.stringify(data,null,2),"application/json")}
function exportCsv(){const rows=state.currentRows||state.resultados,header=["numero","titulo","motricidade","dependencia","classificacao","interpretacao"],lines=[header.join(";")];rows.forEach(r=>lines.push([r.numero,`"${String(r.titulo||"").replaceAll('"','""')}"`,r.motricidade,r.dependencia,`"${String(r.classificacao||"").replaceAll('"','""')}"`,`"${String(r.interpretacao||"").replaceAll('"','""')}"`].join(";")));downloadText("motricidade_md2036.csv",lines.join("\n"),"text/csv;charset=utf-8")}
async function loadAll(){setStatus("Carregando dados...","info");await loadPesquisa();await loadEventos();await loadInfluencias();await loadResultados();renderMatrix();renderChart();renderClassifications();setStatus("Dados carregados. A matriz já está preenchida com valores iniciais.","success")}
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("reloadBtn").addEventListener("click",()=>loadAll().catch(e=>setStatus(e.message,"error")));document.getElementById("recalcBtn").addEventListener("click",recalcLocal);document.getElementById("saveBtn").addEventListener("click",()=>saveMatrix().catch(e=>setStatus(e.message,"error")));document.getElementById("exportJsonBtn").addEventListener("click",exportJson);document.getElementById("exportCsvBtn").addEventListener("click",exportCsv);document.getElementById("matrixBody").addEventListener("change",e=>{if(e.target.classList.contains("matrix-select"))recalcLocal()});loadAll().catch(e=>{console.error(e);setStatus(e.message,"error")})});
